### ISSUE TITLE
`Newtonsoft` could not be found

### ISSUE THREAD

**Issue by kissisnecessary** [starryforest-ymxk/StarryFramework#1]
Got this error:

Assets\StarryFramework\Framework\Runtime\Save Module\SaveComponent.cs(1,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

![ResReader](https://github.com/user-attachments/assets/4ba83c4e-6c8e-4ae5-9926-7ddd148eb94a)

**Comment by Youone003** [comment]
It shall be a package named "Newtonsoft Json" , you can try install it in package manager. It aims to deal with json data.

**Comment by starryforest-ymxk** [comment]
In this version, I mistakenly imported "Newtonsoft Json"， so you can just delete that line of code
