### ISSUE TITLE
API Documentation and Usage Examples

### ISSUE THREAD

**Issue by pingdoom** [starryforest-ymxk/StarryFramework#2]
The StarryFramework project provides a promising set of tools for Unity game development. However, the current documentation lacks detailed information about API usage and real-world implementation examples.

Put my two cents:

1. Provide a comprehensive API reference for each module
2. Include code snippets demonstrating common use cases
3. Create a "Getting Started" guide with a simple example project
4. Add more in-depth explanations of key concepts and design patterns used in the framework

These enhancements would greatly benefit developers looking to integrate StarryFramework into their projects and help showcase the full potential of the framework.

Thanks!

**Comment by starryforest-ymxk** [comment]
Thank you for your advice! I will add relevant documents in future work
