### ISSUE TITLE
Some issues that occur when starting StarryFramework

### ISSUE THREAD

**Issue by Selakz** [starryforest-ymxk/StarryFramework#3]
在尝试使用StarryFramework时发现了以下问题：
1. 如果不使用提供的一些模块，会报Error：
![Exception when not using some modules](https://github.com/user-attachments/assets/37db28e5-5457-47c5-b631-7ad21812cb23)

2. 启动场景时如果没有安装Audio Module但声明使用该模块，会频繁出现以下异常：
![Exception when using an extension but not installing it](https://github.com/user-attachments/assets/a9c98a5a-c2a7-40b1-a323-f5f0023c7152)

3. 由于GameFramework场景里自带了一个Camera，因此当加载同样有Camera的新场景时会出现Two AudioListeners问题（虽然我不知道为什么图中的提示在使用了StarryFramework后就不出现了）：
![Two audioListeners](https://github.com/user-attachments/assets/7365f3c4-0794-4cd6-a787-57d40e6c2500)

4. 提供的默认进度条动画在场景加载完成后按任意键无法进入：
![Example loadbar](https://github.com/user-attachments/assets/1832ab49-6e55-4f44-85c1-ae3850f53190)

**Comment by Selakz** [comment]
我在#4 中尝试解决了这些问题，希望能对项目有些帮助🙏

另外好奇问一句项目中的"Extention"只是个typo还是另有深意（

**Comment by starryforest-ymxk** [comment]
非常感谢，那个是Extension之前拼错了🙌下个版本改回来
